# Page tree
pages:
  - Overview: index.md
  - Release Notes: release-notes.md
  - Repository Pattern:
      - Quick Start: repository/intro.md
      - Reference: repository/ref.md
      - Databinding: repository/databinding.md
  - Mango Query: queries-mango.md
  - Rest Api: rest.md
  - Async: async.md
  - Toolbox:
      - Id Generation: id-generation.md
      - GormUtils Class: gorm-utils.md
      - Bean Path Tools: beanPathTools.md
      - Date Utils: working-with-dates.md
  - Testing: testing.md
  - API Docs: api-docs.md
  - Useful Links: usefulLinks.md

# Project information
site_name: Gorm Tools Grails Plugin
site_description: Plugin tools Grails/Gorm - repository data services, json query language, fast data binder
site_author: 9ci
site_url: https://yakworks.github.io/gorm-tools/
copyright: 'Copyright &copy; 2020 9ci Inc'

## edit link settings
repo_name: yakworks/gorm-tools
repo_url: https://github.com/yakworks/gorm-tools
edit_uri: edit/master/docs/

extra:
  version: '6.1.12-v.1' #'@version@'
  # adds <meta name="robots" content="noindex,nofollow"> to keep search engines from indexing this
  # noindex: true
  palette:
    primary: 'light green'
    accent: indigo


# Project information
#site_name: '@title@'
#site_description: '@description@'
#site_author: '@author@'
#site_url:
#copyright: 'Copyright &copy; 2017 9ci Inc'

## edit link settings
# repo_name: '@gitHubSlug@'
# gradle will replace this url, has to be here for testing though
# repo_url: https://github.com/org/project
# edit_uri: edit/master/docs/

# Config
#docs_dir: 'docs'
#theme: material-components
