apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME} # a name for the deployment
  namespace: ${KUB_NAMESPACE}
  labels:
    app: ${APP_NAME} # tag with the app:grello, labels are kind of like tags
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  selector:
    matchLabels:
      app: ${APP_NAME} # points to label key in pod template below
  template: # pod template
    metadata:
      name: ${APP_NAME}-pod
      labels:
        app: ${APP_NAME} # the pod key label, labels are like tags
    spec: # containers in the pod
      imagePullSecrets:
      - name: 9cibot-dockerhub
      containers:
      - image: ${DOCKER_APP_URL}
        imagePullPolicy: Always
        name: ${APP_NAME}-grails-app #just normal docker name
        # uncomment the LOGGING_CONFIG to enable
        env:
          - name: LOGGING_CONFIG
            value: '/app/logging/logback.groovy'
          - name: APP_PROPS
            value: |+
              grails.serverURL=https://${KUB_INGRESS_URL}

        ports:
          - containerPort: 8080
            name: server
          - containerPort: 8081
            name: jmx
        volumeMounts:
          - mountPath: "/app/logging"
            name: ${APP_NAME}-logback
          - mountPath: "/ninebox"
            name: nfs-ninebox
      volumes:
        - name: ${APP_NAME}-logging
          configMap:
            name: ${APP_NAME}-logback
