# circleCI build file
version: 2.1
jobs:
  build:
    docker:
      - image: yakworks/alpine-jdk:builder8
    resource_class: 'medium+'
    steps:
      - checkout
      - run: &gradle-cache-key ./build.sh catKeyFiles
      - restore_cache: &gradle-cache-restore
          key: gradle-{{ checksum "cache-checksum.tmp" }}

      - run:
          name: ✔︎ Dependencies and Compile
          command: ./gradlew resolveConfigurations --no-daemon

      - save_cache:
          paths: [ "~/.m2", "~/.gradle" ]
          key: gradle-{{ checksum "cache-checksum.tmp" }}

      - run:
          name: ✔︎ Dependencies and Compile
          command: ./gradlew check

      - run:
          name: ✔︎ -- Checks Full Run Tests [gradle check]
          command: ./build.sh check

      - run:
          name: ✔︎ -- Publish plugin if on releasable branch
          command: ./build.sh ciPublishLib

      - store_test_results:
          path: gorm-tools/build/test-results/
      - store_artifacts:
          path: gorm-tools/build/reports/
          destination: gorm-tools
      - store_test_results:
          path: gorm-tools-rest/build/test-results/
      - store_artifacts:
          path: gorm-tools-rest/build/reports/
          destination: gorm-tools
      - store_test_results:
          path: gorm-tools-security/build/test-results/
      - store_artifacts:
          path: gorm-tools-security/build/reports/
          destination: gorm-tools-security
      - store_test_results:
          path: rally-domain/build/test-results/
      - store_artifacts:
          path: rally-domain/build/reports/
          destination: rally-domain
      - store_test_results:
          path: examples/testify/build/test-results/
      - store_artifacts:
          path: examples/testify/build/reports/
          destination: testify
      - store_test_results:
          path: examples/restify/build/test-results/
      - store_artifacts:
          path: examples/restify/build/reports/
          destination: restify
  docs:
    docker:
      - image: yakworks/docmark
    steps:
      - checkout
      - restore_cache: # prior Build job run
          key: build-{{ .Branch }}-{{ .Revision }}
      - compare-url/reconstruct
      - run: ./build.sh ciPublishDocs

orbs:
  compare-url: iynere/compare-url@1.2.0

workflows:
  build-flow:
    jobs:
      - build:
          context: bot-context #context with shared ENV vars
      - docs:
          context: bot-context
          # requires: [build, gorm-tools, gorm-tools-rest, gorm-tools-security, rally-domain, testify]
          requires: [build]
          filters:
            branches: { only: [ master, /release\/.*/ ] }
