# circleCI build file
version: 2.1
jobs:
  build:
    docker:
      - image: yakworks/alpine-java:jdk8-builder

    environment:
      GRADLE_OPTS: "-Xmx1536m -Dorg.gradle.daemon=false" #daemon false doesn't seem to get picked up by fork
      TERM: dumb

    parallelism: 1

    steps:
      - checkout
      - run: ./build.sh catKeyFiles
      - restore_cache:
          key: gradle-{{ checksum "cache-checksum.tmp" }}

      - run:
          name: ✔︎ Dependencies and Compile
          command: ./build.sh compile

      - save_cache:
          paths: ["~/.m2", "~/.gradle"]
          key: gradle-{{ checksum "cache-checksum.tmp" }}

      - run:
          name: ✔︎ -- Checks Full Run Tests [gradle check]
          command: ./build.sh check

      - compare-url/reconstruct
      - run:
          name: ✔︎ -- Publish plugin if on releasable branch
          command: ./build.sh ciPublishLib

      # saves the build for for next job
      - save_cache:
          paths: [".gradle", "./build"]
          key: build-{{ .Branch }}-{{ .Revision }}

  docs:
    docker:
      - image: yakworks/docmark
    steps:
      # add the openssh so circle can check out and curl so compare-url/reconstruct works
      - run: apk add openssh-client curl
      - checkout
      - restore_cache: # prior Build job run
          key: build-{{ .Branch }}-{{ .Revision }}
      - compare-url/reconstruct
      - run: ./build.sh ciPublishDocs

orbs:
  compare-url: iynere/compare-url@1.2.0

workflows:
  build-flow:
    jobs:
      - build:
          context: bot-context #context with shared ENV vars
      - docs:
          context: bot-context
          requires: [build]
          filters:
            branches: { only: [ publish_test, /release\/.*/ ] }
