# circleCI build file
version: 2.1
jobs:
  build:
    docker:
      - image: yakworks/alpine-jdk:builder8
    resource_class: 'medium+'

    steps:
      - checkout

      - run: make cache-key-file
      - restore_cache:
          key: gradle-{{ checksum "cache-key.tmp" }}

      - run: make resolve-dependencies

      - save_cache:
          paths: [ "~/.m2", "~/.gradle" ]
          key: gradle-{{ checksum "cache-key.tmp" }}

      - run:
          name: ✔︎ -- Test
          command: make check

      # merge test results to store in circle
      - run:
          name: ✔︎ -- Merge Test Results
          when: always
          command: make merge-test-results

      # call orb that creates the CIRCLE_COMPARE_URL.txt
      - compare-url/reconstruct
      - run:
          name: ✔︎ -- Publish plugin if on releasable branch
          command: make publish-release

      - store_test_results:
          path: build/test-results/
      - store_artifacts:
          path: build/test-reports/
          destination: /

  docs:
    docker:
      - image: yakworks/docmark
    steps:
      - checkout
      - restore_cache: # prior Build job run
          key: build-{{ .Branch }}-{{ .Revision }}
      - compare-url/reconstruct
      - run: make publish-docs

orbs:
  compare-url: iynere/compare-url@1.2.0

workflows:
  build-flow:
    jobs:
      - build:
          context: bot-context #context with shared ENV vars
      - docs:
          context: bot-context
          # requires: [build, gorm-tools, gorm-tools-rest, gorm-tools-security, rally-domain, testify]
          requires: [build]
          filters:
            branches: { only: [ master, /release\/.*/ ] }
