---
restApi:
  project: # project already exists as a project controller so this just configures it
    includes:
      list: ['id', 'num', 'name', 'billable']
      picklist: ['id', 'num', 'name']

  book: # basic example where all the defaults come either from domain or their stock
    entityClass: restify.Book

  org:
    entityClass: yakworks.taskify.domain.Org
    qSearch: ['num', 'name']
    includes:
      get: ['*', 'type.*']
      picklist: ['id', 'name']

  task:
    entityClass: yakworks.taskify.domain.Task
    qSearch: ['name', 'note']
    includes:
      get: ['*', 'project.*']
