---
restApi:
  project:
    includes:
      default: ['*']
      list: ['id', 'num', 'name', 'billable']
      pickList: ['id', 'num', 'name']
  book:
    entityClass: restify.Book
    qSearch: ['num', 'name']
    includes:
      default: ['*']
      list: ['id', 'num', 'name', 'billable']
      pickList: ['id', 'num', 'name']
  ship:
    entityClass: restify.ShipAddress
