---
restApi:
  project:
    includes:
      default: ['*']
      list: ['id', 'num', 'name', 'billable']
      pickList: ['id', 'num', 'name']

  book:
    entityClass: restify.Book
    qSearch: ['title']
    includes:
      default: ['id', 'title']

  org:
    entityClass: yakworks.taskify.domain.Org
    qSearch: ['num', 'name']
    includes:
      default: ['*', 'type.*']
      pickList: ['id', 'name']

  task:
    entityClass: yakworks.taskify.domain.Task
    qSearch: ['name', 'note']
    includes:
      default: ['*', 'project.*']
