---
restApi:
  # Security
  user:
    description: The Users of the system. Certain limitiations will apply if user has been active
    namespace: security
    entityClass: gorm.tools.security.domain.AppUser
  role:
    description: The system roles that a user can belong to
    namespace: security
    entityClass: gorm.tools.security.domain.SecRole
  roleUser:
    description: The users assigned to the roles
    namespace: security
    allowedMethods: [GET, DELETE, POST]
    entityClass: gorm.tools.security.domain.SecRoleUser

  # Rally
  activity:
    description: {$ref: descriptions/activity.md}
    namespace: rally
    entityClass: yakworks.rally.activity.model.Activity
  attachment:
    namespace: rally
    entityClass: yakworks.rally.attachment.model.Attachment
  company:
    namespace: rally
    entityClass: yakworks.rally.orgs.model.Company
  contact:
    namespace: rally
    entityClass: yakworks.rally.orgs.model.Contact
  org:
    namespace: rally
    entityClass: yakworks.rally.orgs.model.Org
    includes:
      get: [ '*', 'info.*' ]
  orgTypeSetup:
    namespace: rally
    entityClass: yakworks.rally.orgs.model.OrgTypeSetup
  tag:
    namespace: rally
    entityClass: yakworks.rally.tag.model.Tag

